#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DisertationProject.Resource", IsApplication=true)]

namespace DisertationProject
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int black = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int blue = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int green = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int red = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_card = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int camera = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_av_do_not_repeat = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_av_do_not_shuffle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_av_fast_forward = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_av_next = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_av_pause = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_av_play = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_av_previous = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_av_repeat = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_av_rewind = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_av_shuffle = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_av_stop = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_launcher = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_stat_av_play_over_video = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int repeatToggleSelector = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int shuffleToggleSelector = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000d
			public const int cameraButton = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int imageView1 = 2131230735;
			
			// aapt resource value: 0x7f080004
			public const int linearLayout1 = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout2 = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout3 = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout4 = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int nextButton = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int pauseButton = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int playButton = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int previousButton = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int repeatButton = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int shuffleButton = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int songListView = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int songPositionSeekBar = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int stopButton = 2131230728;
			
			// aapt resource value: 0x7f08000e
			public const int textView1 = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Jessica_Jay_Casablanca = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Vaya_Con_Dios_Puerto_Rico = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int mp3_url = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int nextText = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int pauseText = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int playText = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int previousText = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int repeatOffText = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int repeatOnText = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int shuffleOffText = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int shuffleOnText = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int stopText = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int suffleText = 2131099654;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int BaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int ButtonStyle = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int Theme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
